name: Call a reusable workflow

on:
  schedule:
    - cron: "0/5 * * * *"
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Build Swift at a tagged snapshot'
        default: false
        type: boolean   

jobs:
  call-workflow-main:
    uses: hyp/test-branch-workflow/.github/workflows/simple.yml@main
  call-workflow-510:
    uses: hyp/test-branch-workflow/.github/workflows/simple.yml@release/5.10