name: Call a reusable workflow

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Build Swift at a tagged snapshot'
        default: false
        type: boolean

jobs:
  call-workflow-passing-data:
    uses: hyp/test-branch-workflow/.github/workflows/simple.yml@main
    with:
      snapshot: ${{ github.event.inputs.snapshot }}