name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      snapshot:
        description: 'Build Swift at a tagged snapshot'
        default: false
        type: boolean   

jobs:
  call-workflow-passing-data:
    uses: hyp/test-branch-workflow/.github/workflows/simple.yml@${{matrix.branch}}
    with:
      snapshot: ${{ inputs.snapshot }}
    strategy:
      matrix:
        branch:
          - main