name: Call a reusable workflow

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  call-workflow-main:
    uses: hyp/test-branch-workflow/.github/workflows/simple.yml@main
  call-workflow-510:
    uses: hyp/test-branch-workflow/.github/workflows/simple.yml@release/5.10